### ISSUE TITLE
Dropbox link to download photoshopCC-V19.1.6-2018x64.tgz is broken

### ISSUE THREAD

**Issue by ProttoyAD** [Gictorbit/photoshopCClinux#40]
Hi. Can someone give me any alternative link to download .? This link [www.dropbox.com/s/dwfyzq2ie6jih7g/photoshopCC-V19.1.6-2018x64.tgz?dl=1] isn't working or the file is removed .

**Comment by Gictorbit** [comment]
hi I checked download URL and it's valid and downloadable.
can you download file directly using `aria2c`? you can check with command below:
`aria2c https://www.dropbox.com/s/dwfyzq2ie6jih7g/photoshopCC-V19.1.6-2018x64.tgz\?dl\=1`

anyway if you need an alternative link here it is
[photoshopCC-V19.1.6-2018x64.tgz](http://dl.gictor.ir/photoshopCC-V19.1.6-2018x64.tgz)

**Comment by dxndvndxn** [comment]
Hi, thanks man!!
But I used another tutorial. This video helped me
https://youtu.be/R6qWgKC6DsY

**Comment by ProttoyAD** [comment]
yeah thanks man...i tried again and this time it worked...by the way could
you please do the same for illustrator..??? um tired of dual boot..its a
real pain in the ass...

**Comment by Gictorbit** [comment]
> yeah thanks man...i tried again and this time it worked...

very well sounds nice

> by the way could you please do the same for illustrator..???

I tried the various version of illustrator and it was unusable because of `wine` errors.
and as you know illustrator performance depends on gpu so...
if I found a way for it I will do it

**Comment by Mid4s-dev** [comment]
how do i get the download link for "replacement.tgz"

**Comment by GeneralVirtenow** [comment]
> how do i get the download link for "replacement.tgz"

I think this link should work
https://victor.poshtiban.io/p/gictor/photoshopCC/replacement.tgz

**Comment by als-creator** [comment]
where should photoshop be placed after manually downloading the file? i have a problem with uploading too
![ksnip_20230101-151328](https://user-images.githubusercontent.com/25702710/210165974-469bff1f-8840-4034-87dc-46eb821be006.png)

**Comment by successtheman** [comment]
> where should photoshop be placed after manually downloading the file? i have a problem with uploading too ![ksnip_20230101-151328](https://user-images.githubusercontent.com/25702710/210165974-469bff1f-8840-4034-87dc-46eb821be006.png)

The tgz goes in `~/.cache/photoshopCCV19/` if you want to predownload it/place it manually, the script seems to recognize it exists and extract it if you run the PhotoshopSetup.sh. Regardless after installing I was unable to get the program to start says unrecoveable error so I uninstalled it

**Comment by als-creator** [comment]
i installed aria2c and the script loads photoshop normally, i also checked manual loading in ~/.cache/photoshopCCV19/, this option also works

**Comment by popoopendoor** [comment]
> > how do i get the download link for "replacement.tgz"
> 
> I think this link should work https://victor.poshtiban.io/p/gictor/photoshopCC/replacement.tgz

sorry
This link I can not open, please give me a 'replacement.tgz' download link

**Comment by abrarzha** [comment]
replacement.tgz https://drive.google.com/file/d/1AD_a6XfaiFY_eivEMdCajvjxRC-1P-NY/view?usp=sharing

**Comment by enlinea777** [comment]
> > how do i get the download link for "replacement.tgz"
> 
> I think this link should work https://victor.poshtiban.io/p/gictor/photoshopCC/replacement.tgz

link is broken

**Comment by intexcor** [comment]
дайте кто нибудь файл, потому что сайт не работает

**Comment by als-creator** [comment]
> дайте кто нибудь файл, потому что сайт не работает

выше есть ссылки https://www.dropbox.com/scl/fi/m5vel80ox1s2yir41fh3b/photoshopCC-V19.1.6-2018x64.tgz?rlkey=l3icq5ky01bm4b4l92i1kyn02&dl=0

**Comment by intexcor** [comment]
да я пока ждал уже свой скрипт установки фотошопа написал. работает кста лучше чем этот и версия новее

> > дайте кто нибудь файл, потому что сайт не работает
> 
> выше есть ссылки https://www.dropbox.com/scl/fi/m5vel80ox1s2yir41fh3b/photoshopCC-V19.1.6-2018x64.tgz?rlkey=l3icq5ky01bm4b4l92i1kyn02&dl=0

**Comment by als-creator** [comment]
я думал еще одна репа будет со старым фотошопом

**Comment by intexcor** [comment]
> я думал еще одна репа будет со старым фотошопом

21 не старый

**Comment by als-creator** [comment]
19 старый, речь же про него шла

**Comment by 716boy** [comment]
читать (на английском языке для лучшего перевода всем)

i solved it, here is a list of how i did


download files to desktop folder

illustratorCC17.tgz here

https://drive.google.com/file/d/1Ayl4wx340qAiARsVy5z0B8dbuNf9DM5u/view?usp=drive_link

if that link does not works use this

https://downloads.runebase.io/illustratorCC17.tgz 

photoshopCC-V19.1.6-2018x64.tgz here

https://drive.google.com/file/d/1OwRUXsQUrOeK000IQSmCcV2enWQ8GYEo/view?usp=drive_link

if google blow my link use this

https://www.dropbox.com/scl/fi/m5vel80ox1s2yir41fh3b/photoshopCC-V19.1.6-2018x64.tgz?rlkey=l3icq5ky01bm4b4l92i1kyn02&dl=0


replacement.tgz here

https://drive.google.com/file/d/1oiM7BA0w9lm0bpfQOQCwEfyZuOTRg9pt/view?usp=drive_link

if google blow my link use this

replacement.tgz https://drive.google.com/file/d/1AD_a6XfaiFY_eivEMdCajvjxRC-1P-NY/view?usp=sharing

go to your usename folder for example

mine is alan

in " alan"(the name of your user) you are gonna find the folder illustratorCClinux or photoshopCClinux, go in the folder needed depends of what are you installing, for example here we are installing photoshop

so we go to photoshopCClinux, however all programs (photoshop or adobeillustrator) they have the same folders, okay

go to photoshopCClinux

then go to scripts and then go to PhotoshopSetup.sh or

illustratorSetup.sh (depends if you are installig photoshop or illustrator)

ok open the sh file

find this line

"local filelink=" you will see something like an "https://whatever.io" it means you gonna replace that line with 

with file:///home/alan/Desktop/replacement.tgz (this in photoshop)

and 

with file:///home/alan/Desktop/photoshopCC-V19.1.6-2018x64.tgz

what you are doing here is, instead of downloading, you are telling the script to use the file you downloaded from above, which is now in your device, i recommend you put all the files "replacement.tgz, photoshopCC-V19.1.6-2018x64.tgz or illustratorCC17.tgz" in desktop folder on your linux so it will be easy, ok then replace with those lines always remember to triple check your file location (again i recomend you to download it to desktop)


here is an example of the lines you will find in both scripts and how it will look after replaced

function replacement() {
    local filename="replacement.tgz"
    local filemd5="6441a8e77c082897a99c2b7b588c9ac4"
    local filelink="file:///home/alan/Desktop/replacement.tgz"
    local filepath="$CACHE_PATH/$filename"

    download_component $filepath $filemd5 $filelink $filename

    mkdir "$RESOURCES_PATH/replacement"
    show_message "extract replacement component..."
    tar -xzf $filepath -C "$RESOURCES_PATH/replacement"

    local replacefiles=("IconResources.idx" "PSIconsHighRes.dat" "PSIconsLowRes.dat")
    local destpath="$WINE_PREFIX/drive_c/users/$USER/PhotoshopSE/Resources"
    
    for f in "${replacefiles[@]}";do
        local sourcepath="$RESOURCES_PATH/replacement/$f"
        cp -f "$sourcepath" "$destpath" || error "cant copy replacement $f file..."
    done

    show_message "replace component compeleted..."
    unset filename filemd5 filelink filepath
}

function install_photoshopSE() {
    local filename="photoshopCC-V19.1.6-2018x64.tgz"
    local filemd5="b63f6ed690343ee12b6195424f94c33f"
    local filelink="file:///home/alan/Desktop/photoshopCC-V19.1.6-2018x64.tgz"
    # local filelink="http://127.0.0.1:8080/photoshopCC-V19.1.6-2018x64.tgz"
    local filepath="$CACHE_PATH/$filename"


    i hope it can be of help to you  

    fully working 7-12dec-24

**Comment by yoelmar34** [comment]
Hi friends, I'm getting an error saying Wine64 isn't installed. I've checked if it's installed, but it's not recognized. I reinstalled Wine64, but it still isn't recognized in Linux Mint.
