### ISSUE TITLE
Pen pressure is not working

### ISSUE THREAD

**Issue by lamduong33** [Gictorbit/photoshopCClinux#7]
As stated in the title, pen pressure will work on Krita, for example, but not CClinux. input-wacom, lib-wacom and xf86-input-wacom are installed. Using a Wacom Intuos S. Running on Ubuntu 20.04.

**Comment by Gictorbit** [comment]
hi thanks for your report
actually I don't have `pen pressure` so I didn't test it on photoshop
as I wrote in readme the installer script uses `wine` in behind the scene to run photoshop which is kind of windows simulator so it depends on `Wacom driver` for windows and `wine pen pressure support`
unfortunately, I can't fix the issue right now because It's a wine problem and  I haven't `pen pressure` to test things

**Comment by PaulCoolDQueenLeon** [comment]
Heya! I found a way to make it work!
Install the OpenTabletDriver, make all the stuff for recognize your tablet, then make it as relative mode, this worked for me, but sometimes it just stop working and I need to restart the Photoshop or make it as another mode and change to relative again.
If this don't work make the thing of Photoshop stop using the Windows Ink or install the Windows Ink in the Plugins Manager of OpenTabletDriver.
I don't know if this will work for everyone, and I didn't saw anyone saying about that as well, so yeah... ._;
Good luck and have fun painting/drawing using Photoshop! Ty~~
