### ISSUE TITLE
Is this software legal?

### ISSUE THREAD

**Issue by NWinXP** [Gictorbit/photoshopCClinux#81]
I have been wondering if this is legal. The bash script (setup.sh) downloads a modified version of the program without the need to activate it, essentially giving you access to the program for free, with no Adobe CC subscription fee. This is practically piracy, so I assume this project is illegal. If so, I will remove the application from my Arch Linux machine.

**Comment by Gictorbit** [comment]
I tested many versions of photoshop.
For software activation we need Adobe Creative Cloud and this process throws some issues while using wine. So a better solution was using an activated version of photoshop and I just found a version of photoshop cc that worked fine on wine
as I liked Linux I wanted to use some adobe products on it because I'm comfortable with its UI.also I know there are great open source alternatives for photoshop on Linux like gimp, ...
I respect them and open source 
I'm not sure about piracy if you doubtful about it, you can remove this
the goal of this repo is to show how much people need adobe products on Linux, and they should release an edition for gnu/linux even close source
